{
	"A" :
	[
		"",
		resolveTreasure({roll: "D20", desc: "CP"}),
		resolveTreasure({roll: "2D20", desc: "CP"}),
		resolveTreasure({roll: "3D20", desc: "CP"}),
		resolveTreasure({roll: "4D20", desc: "CP"}),
		resolveTreasure({roll: "5D20", desc: "CP"}),
		resolveTreasure({roll: "D20", desc: "SP"}),
		resolveTreasure({roll: "2D20", desc: "SP"}),
		resolveTreasure({roll: "3D20", desc: "SP"}),
		resolveTreasure({roll: "4D20", desc: "SP"}),
		resolveTreasure({roll: "5D20", desc: "SP"}),
		resolveTreasure({roll: "D20", desc: "GP"}),
		resolveTreasure({roll: "2D20", desc: "GP"}),
		resolveTreasure({roll: "3D20", desc: "GP"}),
		resolveTreasure({roll: "4D20", desc: "GP"}),
		resolveTreasure({roll: "5D20", desc: "GP"}),
		resolveTreasure({roll: "6D20", desc: "GP"}),
		resolveTreasure({roll: "7D20", desc: "GP"}),
		resolveTreasure({roll: "8D20", desc: "GP"}),
		resolveTreasure({roll: "9D20", desc: "GP"}),
		resolveTreasure({roll: "10D20", desc: "GP"})
	],
	"B" :
	[
		"",
		"Fish bone, rotten meat",
		"Broken water skin",
		"Leftover food stuffs",
		"Water skin",
		"Fresh provisions",
		"Bloody rags",
		"Piece of string",
		"Frayed grubby blanket",
		"Bent piece of wire",
		"Gaudy marble or wax chunk",
		"Flint, steel and tinder",
		"Tooth necklace, elven ears",
		"Fishing hook",
		resolveTreasure({roll: "D20/2", desc: "m moldy rope"}),
		resolveTreasure({roll: "D20", desc: " glass stones"}),
		"Gem Shards (D20 CP)",
		resolveTreasure({roll: "D20", desc: "CP"}, {roll: "D20", desc: "SP"}),
		resolveTreasure({roll: "D20", desc: "CP"}, {roll: "D20", desc: "SP"}, {roll: "D20", desc: "GP"}),
		resolveTreasure({roll: "D20", desc: "GP"}, {resolve: "M:5"}),
		resolveTreasure({roll: "D20", desc: " Gems (D20 GP)"})
	],
	"C" :
	[
		"",
		"Water skin or leather cup",
		"Flint, steel and tinder",
		"One ration",
		resolveTreasure({roll: "D20/2", desc: " torches"}),
		"Blanket or tankard",
		"Fishing rod or wooden cutlery",
		"Leather cord or D20 CP",
		"Pan or pot",
		"Firewood or D20 SP",
		resolveTreasure({roll: "D20/2", desc: " rations"}),
		"Needle and thread or beer keg",
		"D20/2 Meter rope or D20 GP",
		"Healing herb or pipe with tobacco",
		"Climbing gear or oil latern",
		resolveTreasure({resolve: "M:5"}),
		"2 man tent or bear trap",
		resolveTreasure({resolve: "A:15"}),
		"Compass or gold teeth (D20/2 GP)",
		"D20/2 Healing herbs or Ring (D20GP)",
		resolveTreasure({resolve: "M:10"})
	],
	"D" :
	[
		"",
		"1 CP",
		"Bread crumbs or comb",
		"Piece of kohl or leather pouch",
		"Piece of wire or handkerchief (used)",
		"Packaged bread or apple",
		"Wooden figurine or dice",
		"Pipe with tobacco or bandana",
		"Wooden figurine or dice",
		"Crowbar or key",
		"D20 CP or a ring (1SP)",
		"Decorative belt buckle (D20/2 SP)",
		"1 healing herb or deck of cards",
		"Hidden dagger or necklace (D20 SP)",
		"Golden tooth (1GP) or lantern",
		"5 lock picks or bunch of keys",
		resolveTreasure({resolve: "A:15"}),
		"Gold teeth (D20/2 GP) or Healing potion",
		"Precious Jewelry (D20 GP)",
		resolveTreasure({resolve: "M:5"}),
		resolveTreasure({resolve: "M:10"})
	]
}